#ifndef PJLINKNATIVELIBRARY_GLOBAL_H
#define PJLINKNATIVELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PJLINKNATIVELIBRARY_LIBRARY)
#  define PJLINKNATIVELIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define PJLINKNATIVELIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // PJLINKNATIVELIBRARY_GLOBAL_H
