/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wolfram_jlink_NativeLink_JLinkShutdownThread */

#ifndef _Included_com_wolfram_jlink_NativeLink_JLinkShutdownThread
#define _Included_com_wolfram_jlink_NativeLink_JLinkShutdownThread
#ifdef __cplusplus
extern "C" {
#endif
#undef com_wolfram_jlink_NativeLink_JLinkShutdownThread_MIN_PRIORITY
#define com_wolfram_jlink_NativeLink_JLinkShutdownThread_MIN_PRIORITY 1L
#undef com_wolfram_jlink_NativeLink_JLinkShutdownThread_NORM_PRIORITY
#define com_wolfram_jlink_NativeLink_JLinkShutdownThread_NORM_PRIORITY 5L
#undef com_wolfram_jlink_NativeLink_JLinkShutdownThread_MAX_PRIORITY
#define com_wolfram_jlink_NativeLink_JLinkShutdownThread_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
